### ISSUE TITLE
有几个问题提下

### ISSUE THREAD

**Issue by Wuou** [victorzhgx/oauth2#1]
1、使用code模式，用code获取access_token post返回json数据中为什么没有返回refresh_token?

2、使用access_token为什么访问资源数据库的接口products取不到数据？提示
{
    "error": "invalid_token",
    "error_description": "Invalid access token: b52acfcf-07f8-4a6d-a3c0-13758f64c815"
}

**Comment by victorzhgx** [comment]
1、如果过期会自动刷新token
2、这个token失效了。可能是你重启了服务吧
